export const incomeTypes = [
  { id: "i0", name: "Seleccionar" },
  { id: "i1", name: "Diezmos" },
  { id: "i2", name: "Culto Dominical" },
  { id: "i3", name: "Culto de Oración" },
  { id: "i4", name: "Escuela Biblica" },
  { id: "i5", name: "Literatura Biblica" },
  { id: "i6", name: "Ministerio de Jovenes" },
  { id: "i7", name: "Ministerio de Damas" },
  { id: "i8", name: "Ministerio de Caballeros" },
  { id: "i9", name: "Ministerio de Misiones" },
  { id: "i10", name: "Ministerio de Música" },
  { id: "i11", name: "Colegio Evagelico Emmanuel" },
  { id: "i12", name: "Actividades o eventos" },
  { id: "i13", name: "Actividades Misioneras" },
  { id: "i14", name: "Dorcas" },
];
